server:
  port: 8088
spring:
  application:
    name: api-gateway
  #gateway配置
  cloud:
    gateway:
      routes: #路由规则
        - id: order_route #路由的唯一标识 先路由到订单
          uri: lb://greenbelt-service #需要转发的地址 lb就是使用nacos本地负载均衡策略
          predicates:  #断言规则 用于路由规则的匹配
            - Path=/order/**
          # 跨域配置
          globalcors:
            cors-configurations:
              '[/**]': #允许跨域访问的资源
                allowedOrigins: "*"                 #跨域的来源
                allowedMethods:
                  - GET
                  - POST

    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos
    sentinel:
      transport:
        dashboard: 127.0.0.1:9090
          #scg:
        #fallback:
        #mode: response
        #response-body: "{code:'',message:''}"