server:
    port: 9090
spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123456
        url: jdbc:mysql://localhost:3306/GreenBelt?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2b8
        username: root
    application:
        name: greenbelt-service
    cloud:
        nacos:
            service-addr: localhost:8848
            discovery:
                username: nacos
                password: nacos
                namespace: public
                ephemeral: true
    redis:
        timeout: 5000
        host: localhost
        port: 6379
        password: 000415
